version: '3.3'

services:
  portainer:
    image: portainer/portainer-ce
    hostname: portainer
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/portainer:/data
    ports:
      - 9000:9000
      - 8000:8000
    networks:
      - mainnet

  nginx:
    build: ./docker/nginx
    hostname: nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/letsencrypt/:/etc/letsencrypt/
      - ./docker/nginx/certbot/:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - mainnet

networks:
  mainnet:
    driver: bridge